[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "@solmate/=dependencies/solmate-6.8.0/src/",
    "forge-std/=dependencies/forge-std-1.9.6/src/",
]

[dependencies]
solmate = "6.8.0"
forge-std = "1.9.6"

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_version = false
remappings_prefix = "@"
remappings_location = "config"
recursive_deps = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
